Check latest tagged version (#6)
Check all three places with version.
No more 🤦‍♂️

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,6 +33,18 @@ jobs:
           composer run plugin:zip -- --file=build.zip
           unzip build.zip
 
+      - name: "Check latest tagged version"
+        if: ${{ github.event_name == 'release' }}
+        run: |
+          LATEST_TAG="${{ github.ref_name }}"
+          HEADER_VERSION="v$(sed -n -e '0,/^\s*\* Version:\s\+\([0-9].\+\)$/ s##\1#p' syntatis-feature-flipper.php)"
+          PLUGIN_VERSION="v$(sed -n -e "0,/^const PLUGIN_VERSION = '\\([0-9].\\+\\)';$/ s##\\1#p" syntatis-feature-flipper.php)"
+          README_VERSION="v$(sed -n -e '0,/^Stable tag: \([0-9].\+\)$/ s##\1#p' readme.txt)"
+          if [ "${LATEST_TAG}" != "${HEADER_VERSION}" ] || [ "${LATEST_TAG}" != "${PLUGIN_VERSION}" ] || [ "${LATEST_TAG}" != "${README_VERSION}" ]; then
+            echo "::error::Latest tag differs from current version"
+            exit 10
+          fi
+
       - name: Deploy to WordPress.org
         uses: 10up/action-wordpress-plugin-deploy@stable
         with:
