Test version check

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,17 +21,17 @@ jobs:
           php-version: "7.4"
           tools: composer:v2
 
-      - name: Install dependencies
-        run: |
-          npm install
-          composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
+      # - name: Install dependencies
+      #   run: |
+      #     npm install
+      #     composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
 
-      - name: Build plugin
-        run: |
-          npm run build
-          composer run build
-          composer run plugin:zip -- --file=build
-          unzip build.zip -d build
+      # - name: Build plugin
+      #   run: |
+      #     npm run build
+      #     composer run build
+      #     composer run plugin:zip -- --file=build
+      #     unzip build.zip -d build
 
       - name: "Check latest tagged version"
         if: ${{ github.event_name == 'release' }}
@@ -40,18 +40,22 @@ jobs:
           HEADER_VERSION="v$(sed -n -e '0,/^\s*\* Version:\s\+\([0-9].\+\)$/ s##\1#p' syntatis-feature-flipper.php)"
           PLUGIN_VERSION="v$(sed -n -e "0,/^const PLUGIN_VERSION = '\\([0-9].\\+\\)';$/ s##\\1#p" syntatis-feature-flipper.php)"
           README_VERSION="v$(sed -n -e '0,/^Stable tag: \([0-9].\+\)$/ s##\1#p' readme.txt)"
-          if [ "${LATEST_TAG}" != "${HEADER_VERSION}" ] || [ "${LATEST_TAG}" != "${PLUGIN_VERSION}" ] || [ "${LATEST_TAG}" != "${README_VERSION}" ]; then
-            echo "::error::Latest tag differs from current version"
-            exit 10
-          fi
+          echo $LATEST_TAG
+          echo $HEADER_VERSION
+          echo $PLUGIN_VERSION
+          echo $README_VERSION
+          # if [ "${LATEST_TAG}" != "${HEADER_VERSION}" ] || [ "${LATEST_TAG}" != "${PLUGIN_VERSION}" ] || [ "${LATEST_TAG}" != "${README_VERSION}" ]; then
+          #   echo "::error::Latest tag differs from current version"
+          #   exit 10
+          # fi
 
-      - name: Deploy to WordPress.org
-        uses: 10up/action-wordpress-plugin-deploy@stable
-        with:
-          dry-run: ${{ github.event_name != 'release' }}
-        env:
-          ASSETS_DIR: .wporg
-          BUILD_DIR: build
-          SLUG: ${{ env.PLUGIN_SLUG }}
-          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
-          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
+      # - name: Deploy to WordPress.org
+      #   uses: 10up/action-wordpress-plugin-deploy@stable
+      #   with:
+      #     dry-run: ${{ github.event_name != 'release' }}
+      #   env:
+      #     ASSETS_DIR: .wporg
+      #     BUILD_DIR: build
+      #     SLUG: ${{ env.PLUGIN_SLUG }}
+      #     SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
+      #     SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
